def calculate(x, y, sign):
    if sign == "+":
        return x + y
    elif sign == "-":
        return x - y
    elif sign == "*":
        return x * y
    elif sign == "/":
        return x / y
    elif sign == "^":
        return x ** y